platform :ios, '8.0'
use_frameworks!

target 'GooglePlaces' do

pod 'GoogleMaps'
pod 'iPhone-AR-Toolkit'

pod 'HDAugmentedReality', :git => 'https://github.com/DanijelHuis/HDAugmentedReality.git'
end

